In [1]:
train_df = pd.read_csv("../../data/datasets/20170416/default/time_series_leveled_9.csv")
train_df.head()

mean      var      max  degree_mean  degree_std      down  horizontal  \
0  29.6173  22.5958  69.2766   125.666667  115.604553  0.000000    0.642857   
1  27.0710  26.3131  70.2337   130.590909  118.552504  0.022727    0.500000   
2  32.6868  27.2595  72.9634   146.083333  137.548855  0.000000    0.472222   
3  29.7387  26.6687  69.1588   154.648649  125.963362  0.000000    0.567568   
4  26.2518  33.2341  73.5575   118.275862  104.465436  0.000000    0.413793   

       left  left_down   left_up        ...          Tue  Wed  Thurs  Fri  \
0  0.309524   0.119048  0.047619        ...            0    0      0    0   
1  0.204545   0.090909  0.136364        ...            0    0      0    0   
2  0.111111   0.000000  0.166667        ...            0    0      0    0   
3  0.243243   0.027027  0.162162        ...            0    0      0    0   
4  0.172414   0.068966  0.241379        ...            0    0      0    0   

   Sat  mean_shift1  var_shift1  max_shift1  degree_mean_shift1  \
0    0     27.82087     21.1866    65.15349          -27.054264   
1    0     -2.54630      3.7173     0.95710            4.924242   
2    0      5.61580      0.9464     2.72970           15.492424   
3    0     -2.94810     -0.5908    -3.80460            8.565315   
4    0     -3.48690      6.5654     4.39870          -36.372787   

   degree_std_shift1  
0           0.603173  
1           2.947951  
2          18.996351  
3         -11.585493  
4         -21.497925  

[5 rows x 62 columns]

In [6]:
label = np.array(train_df["label"]) - 1
print(np.unique(label))
label[:5]

[0 1 2 3 4]


array([3, 3, 3, 3, 3])

In [8]:
one_hot_label = np.eye(5)[label]
print(one_hot_label.shape)
one_hot_label

(3594, 5)


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [9]:
def one_hot_encoding(label_arr, class_size=5):
    return np.eye(class_size)[label_arr]

In [10]:
one_hot_encoding(label)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])